import fs from "node:fs";
import path from "node:path";
import { randomBytes } from "node:crypto";
import { parse as parseEnvFileContents } from "dotenv";
import { resolvePaperclipEnvPath } from "./paths.js";

const JWT_SECRET_ENV_KEY = "PAPERCLIP_AGENT_JWT_SECRET";

function isNonEmpty(value: unknown): value is string {
  return typeof value === "string" && value.trim().length > 0;
}

function parseEnvFile(contents: string) {
  try {
    return parseEnvFileContents(contents);
  } catch {
    return {};
  }
}

function formatEnvValue(value: string): string {
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}

function renderEnvFile(entries: Record<string, string>) {
  const lines = [
    "# Paperclip environment variables",
    "# Generated by Paperclip server",
    ...Object.entries(entries).map(([key, value]) => `${key}=${formatEnvValue(value)}`),
    "",
  ];
  return lines.join("\n");
}

function readEnvEntries(filePath: string): Record<string, string> {
  if (!fs.existsSync(filePath)) return {};
  return parseEnvFile(fs.readFileSync(filePath, "utf-8"));
}

function writeEnvEntries(filePath: string, entries: Record<string, string>) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, renderEnvFile(entries), { mode: 0o600 });
}

export function readAgentJwtSecretFromEnv(): string | null {
  const raw = process.env[JWT_SECRET_ENV_KEY];
  return isNonEmpty(raw) ? raw.trim() : null;
}

export function readAgentJwtSecretFromEnvFile(filePath = resolvePaperclipEnvPath()): string | null {
  const entries = readEnvEntries(filePath);
  const value = entries[JWT_SECRET_ENV_KEY];
  return isNonEmpty(value) ? value.trim() : null;
}

export function ensureAgentJwtSecret(filePath = resolvePaperclipEnvPath()): {
  secret: string;
  created: boolean;
  loadedFromFile: boolean;
  filePath: string;
} {
  const fromEnv = readAgentJwtSecretFromEnv();
  if (fromEnv) {
    return {
      secret: fromEnv,
      created: false,
      loadedFromFile: false,
      filePath,
    };
  }

  const fromFile = readAgentJwtSecretFromEnvFile(filePath);
  if (fromFile) {
    process.env[JWT_SECRET_ENV_KEY] = fromFile;
    return {
      secret: fromFile,
      created: false,
      loadedFromFile: true,
      filePath,
    };
  }

  const secret = randomBytes(32).toString("hex");
  const entries = readEnvEntries(filePath);
  entries[JWT_SECRET_ENV_KEY] = secret;
  writeEnvEntries(filePath, entries);
  process.env[JWT_SECRET_ENV_KEY] = secret;
  return {
    secret,
    created: true,
    loadedFromFile: false,
    filePath,
  };
}
